### ISSUE TITLE
unlimited memlock is being added twice (RDMA)

### ISSUE THREAD

**Issue by A1ve5** [CSC-IT-Center-for-Science/ansible-role-rdma#1]
the unlimited memlock is being added twice on compute nodes because of https://github.com/CSC-IT-Center-for-Science/ansible-system-limits/blob/master/tasks/redhat.yml

**Comment by A1ve5** [comment]
ansible-system-limits isn't being used on fgci playbook although it is in requirements.yml

**Comment by A1ve5** [comment]
Considering the above, is it still a valid issue?

**Comment by martbhell** [comment]
It's in use by these playbooks: compute.yml local.yml login.yml

**Comment by A1ve5** [comment]
ah, ansible-role-system-limits and not ansible-system-limits which is also in requirements.yml
