### ISSUE TITLE
set to disabled by default

### ISSUE THREAD

**Issue by martbhell** [CSC-IT-Center-for-Science/ansible-role-rdma#2]
So that one can have this role added to hosts in a playbook but it only is applied where it is desired.

**Comment by A1ve5** [comment]
Just install/Run if infiniband_available: True

**Comment by martbhell** [comment]
RDMA can be used over ethernet too (RoCE). Do any fgci sites use that?

I'd change it to a "when: rdma_enabled" to not couple it too tightly with infiniband.

If we add the following to this rdma role then we disable it where infiniband is not available. Without having to add a new variable to fgci-ansible.

<pre> 
infiniband_available: False
rdma_enabled: {{ infiniband_availabile }}
</pre>
